name: Dev CI/CD

on:
  push:
    branches: [dev]

permissions:
  contents: read

jobs:
  build:
    runs-on: dev
    permissions:
      pull-requests: write

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 3
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true
      - run: git log --pretty=oneline

      - name: JDK 21을 설치합니다.
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: gradlew 권한을 부여합니다.
        run: chmod +x gradlew

      - name: Gradle을 통해 빌드합니다.
        run: ./gradlew build

      - name: 빌드 파일 deploy 파일로 이동
        run: cp -f build/libs/*.jar /home/ubuntu/deploy/

      - name: 배포 스크립트 실행
        run: | 
          cd /home/ubuntu/deploy
          sh deploy.sh
